### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by majuscule** [duckduckgo/zeroclickinfo-goodie-math#1]
Referencing https://github.com/duckduckgo/zeroclickinfo-goodies/pull/202 @SamWhited

**Comment by SamWhited** [comment]
@nospampleasemam Have you had a chance to actually test thing? I don't know if I've included the JavaScript correctly and I doubt it actually works without the path being tweaked.

**Comment by majuscule** [comment]
No I have not. Going to do so now. Just sent you an email, but it was basically just saying to come here :-)

**Comment by SamWhited** [comment]
Oops, sorry, just got the email. Works for me; thanks!
